### ISSUE TITLE
THE NERF BRIDGE WONT TRain

### ISSUE THREAD

**Issue by eiyike123** [javieryu/nerf_bridge#24]
![Screenshot 2023-11-22 225910](https://github.com/javieryu/nerf_bridge/assets/128630463/cf2dc029-0315-4805-b404-32006b32ca48)
![Screenshot 2023-11-22 225910](https://github.com/javieryu/nerf_bridge/assets/128630463/7563a181-e294-4885-b328-8e909c4f4616)

(nerfstudio) root@eiyike-Precision-5820-Tower-X-Series:/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge# python ros_train.py --method_name ros_nerfacto --data /home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros_config_sample.json --pipeline.datamanager.data_update_freq 1.0

optimizer is no longer specified in the CameraOptimizerConfig, it is now defined with the rest of the param groups 
inside the config file under the name 'camera_opt'

/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros/method_configs.py:42: FutureWarning: above message coming from
  camera_optimizer=CameraOptimizerConfig(

CameraOptimizerConfig has been moved from the DataManager to the Model.

/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros/method_configs.py:36: FutureWarning: above message coming from
  datamanager=ROSDataManagerConfig(

CameraOptimizerConfig has been moved from the DataManager to the Model.

/root/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/tyro/_calling.py:242: FutureWarning: above message coming from
  return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
[04:23:25] Using --data alias for --data.pipeline.datamanager.dataparser.data                            ros_train.py:56
──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────
ROSTrainerConfig(
    _target=<class 'nsros.ros_trainer.ROSTrainer'>,
    output_dir=PosixPath('outputs'),
    method_name='ros_nerfacto',
    experiment_name=None,
    project_name='nerfstudio-project',
    timestamp='2023-11-23_042325',
    machine=MachineConfig(seed=42, num_devices=1, num_machines=1, machine_rank=0, dist_url='auto', device_type='cuda'),
    logging=LoggingConfig(
        relative_log_dir=PosixPath('.'),
        steps_per_log=10,
        max_buffer_size=20,
        local_writer=LocalWriterConfig(
            _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
            enable=True,
            stats_to_track=(
                <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
                <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
                <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
                <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
                <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
                <EventName.ETA: 'ETA (time)'>
            ),
            max_log_size=10
        ),
        profiler='basic'
    ),
    viewer=ViewerConfig(
        relative_log_filename='viewer_log_filename.txt',
        websocket_port=None,
        websocket_port_default=7007,
        websocket_host='0.0.0.0',
        num_rays_per_chunk=20000,
        max_num_display_images=512,
        quit_on_train_completion=False,
        image_format='jpeg',
        jpeg_quality=90,
        make_share_url=False,
        camera_frustum_scale=0.1,
        default_composite_depth=True
    ),
    pipeline=VanillaPipelineConfig(
        _target=<class 'nerfstudio.pipelines.base_pipeline.VanillaPipeline'>,
        datamanager=ROSDataManagerConfig(
            _target=<class 'nsros.ros_datamanager.ROSDataManager'>,
            data=None,
            masks_on_gpu=False,
            images_on_gpu=False,
            dataparser=ROSDataParserConfig(
                _target=<class 'nsros.ros_dataparser.ROSDataParser'>,
                data=PosixPath('/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros_config_sample.json'),
                scale_factor=1.0,
                aabb_scale=0.8
            ),
            train_num_rays_per_batch=4096,
            train_num_images_to_sample_from=-1,
            train_num_times_to_repeat_images=-1,
            eval_num_rays_per_batch=4096,
            eval_num_images_to_sample_from=-1,
            eval_num_times_to_repeat_images=-1,
            eval_image_indices=(0,),
            collate_fn=<function nerfstudio_collate at 0x7f814dae9310>,
            camera_res_scale_factor=1.0,
            patch_size=1,
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='SO3xR3',
                trans_l2_penalty=0.01,
                rot_l2_penalty=0.001,
                optimizer=AdamOptimizerConfig(
                    _target=<class 'torch.optim.adam.Adam'>,
                    lr=0.0006,
                    eps=1e-08,
                    max_norm=None,
                    weight_decay=0.01
                ),
                scheduler=None
            ),
            pixel_sampler=PixelSamplerConfig(
                _target=<class 'nerfstudio.data.pixel_samplers.PixelSampler'>,
                num_rays_per_batch=4096,
                keep_full_image=False,
                is_equirectangular=False
            ),
            publish_training_posearray=True,
            data_update_freq=1.0,
            num_training_images=500
        ),
        model=NerfactoModelConfig(
            _target=<class 'nerfstudio.models.nerfacto.NerfactoModel'>,
            enable_collider=True,
            collider_params={'near_plane': 2.0, 'far_plane': 6.0},
            loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
            eval_num_rays_per_chunk=32768,
            prompt=None,
            near_plane=0.05,
            far_plane=1000.0,
            background_color='last_sample',
            hidden_dim=64,
            hidden_dim_color=64,
            hidden_dim_transient=64,
            num_levels=16,
            base_res=16,
            max_res=2048,
            log2_hashmap_size=19,
            features_per_level=2,
            num_proposal_samples_per_ray=(256, 96),
            num_nerf_samples_per_ray=48,
            proposal_update_every=5,
            proposal_warmup=5000,
            num_proposal_iterations=2,
            use_same_proposal_network=False,
            proposal_net_args_list=[
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False},
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}
            ],
            proposal_initial_sampler='piecewise',
            interlevel_loss_mult=1.0,
            distortion_loss_mult=0.002,
            orientation_loss_mult=0.0001,
            pred_normal_loss_mult=0.001,
            use_proposal_weight_anneal=True,
            use_average_appearance_embedding=True,
            proposal_weights_anneal_slope=10.0,
            proposal_weights_anneal_max_num_iters=1000,
            use_single_jitter=True,
            predict_normals=False,
            disable_scene_contraction=False,
            use_gradient_scaling=False,
            implementation='tcnn',
            appearance_embed_dim=32,
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='SO3xR3',
                trans_l2_penalty=0.01,
                rot_l2_penalty=0.001,
                optimizer=None,
                scheduler=None
            )
        )
    ),
    optimizers={
        'proposal_networks': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'fields': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        }
    },
    vis='viewer',
    data=PosixPath('/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros_config_sample.json'),
    prompt=None,
    relative_model_dir=PosixPath('nerfstudio_models'),
    load_scheduler=True,
    steps_per_save=30000,
    steps_per_eval_batch=500,
    steps_per_eval_image=500,
    steps_per_eval_all_images=25000,
    max_num_iterations=30000,
    mixed_precision=True,
    use_grad_scaler=False,
    save_only_latest_checkpoint=True,
    load_dir=None,
    load_step=None,
    load_config=None,
    load_checkpoint=None,
    log_gradients=False,
    gradient_accumulation_steps=1,
    msg_timeout=60.0,
    num_msgs_to_start=3,
    draw_training_images=False
)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[04:23:26] Saving config to: outputs/unnamed/ros_nerfacto/2023-11-23_042325/config.yml          experiment_config.py:141
           Saving checkpoints to: outputs/unnamed/ros_nerfacto/2023-11-23_042325/nerfstudio_models        trainer.py:134
Traceback (most recent call last):
  File "ros_train.py", line 90, in <module>
    entrypoint()
  File "ros_train.py", line 80, in entrypoint
    main(
  File "ros_train.py", line 67, in main
    trainer.setup()
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros/ros_trainer.py", line 50, in setup
    super().setup(test_mode=test_mode)
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nerfstudio/nerfstudio/engine/trainer.py", line 147, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nerfstudio/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 264, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nerfstudio/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 428, in __init__
    super().__init__()
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 189, in __init__
    self.setup_train()
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros/ros_datamanager.py", line 77, in setup_train
    self.train_ray_generator = RayGenerator(
TypeError: __init__() takes 2 positional arguments but 3 were given
(nerfstudio) root@eiyike-Precision-5820-Tower-X-Series:/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge#

**Comment by javieryu** [comment]
Are you on the latest version of the main branch?

**Comment by eiyike123** [comment]
Yea

**Comment by eiyike123** [comment]
I am on the main branch

**Comment by eiyike123** [comment]
7 months ago.

**Comment by eiyike123** [comment]
ModuleNotFoundError: No module named ‘nerfstudio.configs’

**Comment by SivadineshPonrajan** [comment]
```bash
File "/root/nerf_bridge/nsros/ros_datamanager.py", line 77, in setup_train
    self.train_ray_generator = RayGenerator(
TypeError: __init__() takes 2 positional arguments but 3 were given
```

I am facing the same issue as well. is there any solution yet?
