### ISSUE TITLE
error during training 

### ISSUE THREAD

**Issue by eiyike123** [javieryu/nerf_bridge#28]
optimizer is no longer specified in the CameraOptimizerConfig, it is now defined with the rest of the param groups 
inside the config file under the name 'camera_opt'

/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros/method_configs.py:42: FutureWarning: above message coming from
  camera_optimizer=CameraOptimizerConfig(

CameraOptimizerConfig has been moved from the DataManager to the Model.

/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros/method_configs.py:36: FutureWarning: above message coming from
  datamanager=ROSDataManagerConfig(

CameraOptimizerConfig has been moved from the DataManager to the Model.

/usr/local/lib/python3.8/dist-packages/tyro/_calling.py:245: FutureWarning: above message coming from
  return unwrapped_f(*positional_args, **kwargs), consumed_keywords  # type: ignore
[01:16:16] Using --data alias for --data.pipeline.datamanager.dataparser.data                            ros_train.py:56
──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────
ROSTrainerConfig(
    _target=<class 'nsros.ros_trainer.ROSTrainer'>,
    output_dir=PosixPath('outputs'),
    method_name='ros_nerfacto',
    experiment_name=None,
    project_name='nerfstudio-project',
    timestamp='2024-02-27_011616',
    machine=MachineConfig(seed=42, num_devices=1, num_machines=1, machine_rank=0, dist_url='auto', device_type='cuda'),
    logging=LoggingConfig(
        relative_log_dir=PosixPath('.'),
        steps_per_log=10,
        max_buffer_size=20,
        local_writer=LocalWriterConfig(
            _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
            enable=True,
            stats_to_track=(
                <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
                <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
                <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
                <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
                <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
                <EventName.ETA: 'ETA (time)'>
            ),
            max_log_size=10
        ),
        profiler='basic'
    ),
    viewer=ViewerConfig(
        relative_log_filename='viewer_log_filename.txt',
        websocket_port=None,
        websocket_port_default=7007,
        websocket_host='0.0.0.0',
        num_rays_per_chunk=20000,
        max_num_display_images=512,
        quit_on_train_completion=False,
        image_format='jpeg',
        jpeg_quality=75,
        make_share_url=False,
        camera_frustum_scale=0.1,
        default_composite_depth=True
    ),
    pipeline=VanillaPipelineConfig(
        _target=<class 'nerfstudio.pipelines.base_pipeline.VanillaPipeline'>,
        datamanager=ROSDataManagerConfig(
            _target=<class 'nsros.ros_datamanager.ROSDataManager'>,
            data=None,
            masks_on_gpu=False,
            images_on_gpu=False,
            dataparser=ROSDataParserConfig(
                _target=<class 'nsros.ros_dataparser.ROSDataParser'>,
                data=PosixPath('/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros_config_sample.json'),
                scale_factor=1.0,
                aabb_scale=0.8
            ),
            train_num_rays_per_batch=4096,
            train_num_images_to_sample_from=-1,
            train_num_times_to_repeat_images=-1,
            eval_num_rays_per_batch=4096,
            eval_num_images_to_sample_from=-1,
            eval_num_times_to_repeat_images=-1,
            eval_image_indices=(0,),
            collate_fn=<function nerfstudio_collate at 0x7fa967f4e670>,
            camera_res_scale_factor=1.0,
            patch_size=1,
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='SO3xR3',
                trans_l2_penalty=0.01,
                rot_l2_penalty=0.001,
                optimizer=AdamOptimizerConfig(
                    _target=<class 'torch.optim.adam.Adam'>,
                    lr=0.0006,
                    eps=1e-08,
                    max_norm=None,
                    weight_decay=0.01
                ),
                scheduler=None
            ),
            pixel_sampler=PixelSamplerConfig(
                _target=<class 'nerfstudio.data.pixel_samplers.PixelSampler'>,
                num_rays_per_batch=4096,
                keep_full_image=False,
                is_equirectangular=False,
                ignore_mask=False,
                fisheye_crop_radius=None,
                rejection_sample_mask=True,
                max_num_iterations=100
            ),
            publish_training_posearray=True,
            data_update_freq=5.0,
            num_training_images=500
        ),
        model=NerfactoModelConfig(
            _target=<class 'nerfstudio.models.nerfacto.NerfactoModel'>,
            enable_collider=True,
            collider_params={'near_plane': 2.0, 'far_plane': 6.0},
            loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
            eval_num_rays_per_chunk=32768,
            prompt=None,
            near_plane=0.05,
            far_plane=1000.0,
            background_color='last_sample',
            hidden_dim=64,
            hidden_dim_color=64,
            hidden_dim_transient=64,
            num_levels=16,
            base_res=16,
            max_res=2048,
            log2_hashmap_size=19,
            features_per_level=2,
            num_proposal_samples_per_ray=(256, 96),
            num_nerf_samples_per_ray=48,
            proposal_update_every=5,
            proposal_warmup=5000,
            num_proposal_iterations=2,
            use_same_proposal_network=False,
            proposal_net_args_list=[
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False},
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}
            ],
            proposal_initial_sampler='piecewise',
            interlevel_loss_mult=1.0,
            distortion_loss_mult=0.002,
            orientation_loss_mult=0.0001,
            pred_normal_loss_mult=0.001,
            use_proposal_weight_anneal=True,
            use_appearance_embedding=True,
            use_average_appearance_embedding=True,
            proposal_weights_anneal_slope=10.0,
            proposal_weights_anneal_max_num_iters=1000,
            use_single_jitter=True,
            predict_normals=False,
            disable_scene_contraction=False,
            use_gradient_scaling=False,
            implementation='tcnn',
            appearance_embed_dim=32,
            average_init_density=1.0,
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='SO3xR3',
                trans_l2_penalty=0.01,
                rot_l2_penalty=0.001,
                optimizer=None,
                scheduler=None
            )
        )
    ),
    optimizers={
        'proposal_networks': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'fields': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        }
    },
    vis='viewer',
    data=PosixPath('/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros_config_sample.json'),
    prompt=None,
    relative_model_dir=PosixPath('nerfstudio_models'),
    load_scheduler=True,
    steps_per_save=30000,
    steps_per_eval_batch=500,
    steps_per_eval_image=500,
    steps_per_eval_all_images=25000,
    max_num_iterations=30000,
    mixed_precision=True,
    use_grad_scaler=False,
    save_only_latest_checkpoint=True,
    load_dir=None,
    load_step=None,
    load_config=None,
    load_checkpoint=None,
    log_gradients=False,
    gradient_accumulation_steps={},
    msg_timeout=60.0,
    num_msgs_to_start=3,
    draw_training_images=False
)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[01:16:16] Saving config to: outputs/unnamed/ros_nerfacto/2024-02-27_011616/config.yml          experiment_config.py:136
           Saving checkpoints to: outputs/unnamed/ros_nerfacto/2024-02-27_011616/nerfstudio_models        trainer.py:136
Traceback (most recent call last):
  File "ros_train.py", line 90, in <module>
    entrypoint()
  File "ros_train.py", line 80, in entrypoint
    main(
  File "ros_train.py", line 67, in main
    trainer.setup()
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros/ros_trainer.py", line 50, in setup
    super().setup(test_mode=test_mode)
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/engine/trainer.py", line 149, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/pipelines/base_pipeline.py", line 254, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/data/datamanagers/base_datamanager.py", line 422, in __init__
    super().__init__()
  File "/usr/local/lib/python3.8/dist-packages/nerfstudio/data/datamanagers/base_datamanager.py", line 181, in __init__
    self.setup_train()
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros/ros_datamanager.py", line 77, in setup_train
    self.train_ray_generator = RayGenerator(
TypeError: __init__() takes 2 positional arguments but 3 were given
(nerfstudio2) root@eiyike-Precision-5820-Tower-X-Series:/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge#

**Comment by javieryu** [comment]
Looks like you're using the wrong version of nerfstudio. Try 0.3.4 instead of 1.0.

**Comment by eiyike123** [comment]
is it that same version for ros foxy and humble

**Comment by eiyike123** [comment]
(nerfstudio3) root@eiyike-Precision-5820-Tower-X-Series:/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge# python3 ros_train.py --method_name ros_nerfacto --data /home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros_config_sample.json --pipeline.datamanager.data_update_freq 1.0
[17:40:30] Using --data alias for --data.pipeline.datamanager.dataparser.data                            ros_train.py:56
──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────
ROSTrainerConfig(
    _target=<class 'nsros.ros_trainer.ROSTrainer'>,
    output_dir=PosixPath('outputs'),
    method_name='ros_nerfacto',
    experiment_name=None,
    project_name='nerfstudio-project',
    timestamp='2024-02-27_174030',
    machine=MachineConfig(seed=42, num_devices=1, num_machines=1, machine_rank=0, dist_url='auto', device_type='cuda'),
    logging=LoggingConfig(
        relative_log_dir=PosixPath('.'),
        steps_per_log=10,
        max_buffer_size=20,
        local_writer=LocalWriterConfig(
            _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
            enable=True,
            stats_to_track=(
                <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
                <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
                <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
                <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
                <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
                <EventName.ETA: 'ETA (time)'>
            ),
            max_log_size=10
        ),
        profiler='basic'
    ),
    viewer=ViewerConfig(
        relative_log_filename='viewer_log_filename.txt',
        websocket_port=None,
        websocket_port_default=7007,
        websocket_host='0.0.0.0',
        num_rays_per_chunk=20000,
        max_num_display_images=512,
        quit_on_train_completion=False,
        image_format='jpeg',
        jpeg_quality=90,
        make_share_url=False
    ),
    pipeline=VanillaPipelineConfig(
        _target=<class 'nerfstudio.pipelines.base_pipeline.VanillaPipeline'>,
        datamanager=ROSDataManagerConfig(
            _target=<class 'nsros.ros_datamanager.ROSDataManager'>,
            data=None,
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='SO3xR3',
                position_noise_std=0.0,
                orientation_noise_std=0.0,
                optimizer=AdamOptimizerConfig(
                    _target=<class 'torch.optim.adam.Adam'>,
                    lr=0.0006,
                    eps=1e-08,
                    max_norm=None,
                    weight_decay=0.01
                ),
                scheduler=ExponentialDecaySchedulerConfig(
                    _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                    lr_pre_warmup=1e-08,
                    lr_final=None,
                    warmup_steps=0,
                    max_steps=10000,
                    ramp='cosine'
                ),
                param_group='camera_opt'
            ),
            masks_on_gpu=False,
            images_on_gpu=False,
            dataparser=ROSDataParserConfig(
                _target=<class 'nsros.ros_dataparser.ROSDataParser'>,
                data=PosixPath('/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros_config_sample.json'),
                scale_factor=1.0,
                aabb_scale=0.8
            ),
            train_num_rays_per_batch=4096,
            train_num_images_to_sample_from=-1,
            train_num_times_to_repeat_images=-1,
            eval_num_rays_per_batch=4096,
            eval_num_images_to_sample_from=-1,
            eval_num_times_to_repeat_images=-1,
            eval_image_indices=(0,),
            collate_fn=<function nerfstudio_collate at 0x7ff908d0bb80>,
            camera_res_scale_factor=1.0,
            patch_size=1,
            pixel_sampler=PixelSamplerConfig(
                _target=<class 'nerfstudio.data.pixel_samplers.PixelSampler'>,
                num_rays_per_batch=4096,
                keep_full_image=False,
                is_equirectangular=False
            ),
            publish_training_posearray=True,
            data_update_freq=1.0,
            num_training_images=500
        ),
        model=NerfactoModelConfig(
            _target=<class 'nerfstudio.models.nerfacto.NerfactoModel'>,
            enable_collider=True,
            collider_params={'near_plane': 2.0, 'far_plane': 6.0},
            loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
            eval_num_rays_per_chunk=32768,
            prompt=None,
            near_plane=0.05,
            far_plane=1000.0,
            background_color='last_sample',
            hidden_dim=64,
            hidden_dim_color=64,
            hidden_dim_transient=64,
            num_levels=16,
            base_res=16,
            max_res=2048,
            log2_hashmap_size=19,
            features_per_level=2,
            num_proposal_samples_per_ray=(256, 96),
            num_nerf_samples_per_ray=48,
            proposal_update_every=5,
            proposal_warmup=5000,
            num_proposal_iterations=2,
            use_same_proposal_network=False,
            proposal_net_args_list=[
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False},
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}
            ],
            proposal_initial_sampler='piecewise',
            interlevel_loss_mult=1.0,
            distortion_loss_mult=0.002,
            orientation_loss_mult=0.0001,
            pred_normal_loss_mult=0.001,
            use_proposal_weight_anneal=True,
            use_average_appearance_embedding=True,
            proposal_weights_anneal_slope=10.0,
            proposal_weights_anneal_max_num_iters=1000,
            use_single_jitter=True,
            predict_normals=False,
            disable_scene_contraction=False,
            use_gradient_scaling=False,
            implementation='tcnn',
            appearance_embed_dim=32
        )
    ),
    optimizers={
        'proposal_networks': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'fields': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        }
    },
    vis='viewer',
    data=PosixPath('/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros_config_sample.json'),
    prompt=None,
    relative_model_dir=PosixPath('nerfstudio_models'),
    load_scheduler=True,
    steps_per_save=30000,
    steps_per_eval_batch=500,
    steps_per_eval_image=500,
    steps_per_eval_all_images=25000,
    max_num_iterations=30000,
    mixed_precision=True,
    use_grad_scaler=False,
    save_only_latest_checkpoint=True,
    load_dir=None,
    load_step=None,
    load_config=None,
    load_checkpoint=None,
    log_gradients=False,
    gradient_accumulation_steps=1,
    msg_timeout=60.0,
    num_msgs_to_start=3,
    draw_training_images=False
)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[17:40:30] Saving config to: outputs/unnamed/ros_nerfacto/2024-02-27_174030/config.yml          experiment_config.py:141
           Saving checkpoints to: outputs/unnamed/ros_nerfacto/2024-02-27_174030/nerfstudio_models        trainer.py:134
╭─────────────────────────────────────────── Viewer ───────────────────────────────────────────╮
│        ╷                                                                                     │
│   HTTP │ https://viewer.nerf.studio/versions/23-05-15-1/?websocket_url=ws://localhost:7007   │
│        ╵                                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
No Nerfstudio checkpoint to load, so training from scratch.
Disabled comet/tensorboard/wandb event writers
 (NSROS) Waiting for for image streaming to begin ....
 (NSROS) Dataloader is successfully streaming images!
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 4.7314              
VanillaPipeline.get_train_loss_dict: 4.7306              
Traceback (most recent call last):
  File "ros_train.py", line 90, in <module>
    entrypoint()
  File "ros_train.py", line 80, in entrypoint
    main(
  File "ros_train.py", line 68, in main
    trainer.train()
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 259, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/nerfstudio/engine/trainer.py", line 479, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/nerfstudio/pipelines/base_pipeline.py", line 298, in get_train_loss_dict
    ray_bundle, batch = self.datamanager.next_train(step)
  File "/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge/nsros/ros_datamanager.py", line 92, in next_train
    ray_bundle = self.train_ray_generator(ray_indices)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/nerfstudio/model_components/ray_generators.py", line 56, in forward
    ray_bundle = self.cameras.generate_rays(
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/nerfstudio/cameras/cameras.py", line 463, in generate_rays
    raybundle = cameras._generate_rays_from_coords(
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/nerfstudio/cameras/cameras.py", line 646, in _generate_rays_from_coords
    coord_stack[coord_mask, :] = camera_utils.radial_and_tangential_undistort(
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 641, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2069, in run
    super().run()
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 719, in run
    and self.step()
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 683, in step
    getattr(self, inst.opname)(inst)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2157, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 833, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 957, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 1024, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 1009, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/root/minicondaa3/envs/nerfstudio3/lib/python3.8/site-packages/torch/__init__.py", line 1607, in __call__
    return self.compiler_fn(model_, inputs_, **self.kwargs)
torch._dynamo.exc.BackendCompilerFailed: backend='eager' raised:
TypeError: eager() got an unexpected keyword argument 'mode'

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

(nerfstudio3) root@eiyike-Precision-5820-Tower-X-Series:/home/eiyike/NERF_BRIDGE_WRKSPACE/nerf_bridge

**Comment by javieryu** [comment]
can you verify your nerfstudio is installed correctly? This is a torch compiler error so the issue is unrelated to nerfbridge.

**Comment by eiyike123** [comment]
I am running the setup from a docker container with ubuntu 20.04 and i am using ros noetic. Its training now but i can view it realtime

**Comment by eiyike123** [comment]
> can you verify your nerfstudio is installed correctly? This is a torch compiler error so the issue is unrelated to nerfbridge.

It was installed correctly. and its training now but i cant view it realtime
![Screenshot from 2024-02-27 12-55-54](https://github.com/javieryu/nerf_bridge/assets/128630463/c0e90b01-5ff7-469c-a902-7b6d292dad67)
![Screenshot from 2024-02-27 12-55-46](https://github.com/javieryu/nerf_bridge/assets/128630463/028b4e66-9fdb-47f4-ae9d-b8cb5dcfef0a)

**Comment by javieryu** [comment]
That seems like a docker issue then. Most likely the network is not being shared correctly with the host.

**Comment by eiyike123** [comment]
What is the best way to
Solve it
